server:
  port: 8081

spring:
  application:
    name: zone-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/agms_zone
      database: agms_zone

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka